server:
  port: ${PORT:8761}

## Eureka Server Configuration
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: ${EUREKA_HOST:localhost} #intancia por nombre de s
  server:
    renewal-percent-threshold: 0.90 #90% de heartbeats