server:
  port: ${PORT:8761}

## Eureka Server Configuration
eureka:
  server:
    renewal-percent-threshold: 0.85
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: ${EUREKA_HOST:localhost}